# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c38afde17d4f21280485d5ddb75c59f5f690c518312c48630030b3d68c061f0f24eac51c48dd715e8df4f72822f78aee9a62fafcc464d6f5503a9a14d53a4ba7

test:
  secret_key_base: bbbc05ebdc1eb69e85d27f979adbd37e80798fe215733f3209163332b8992b47d77e3b8c9c65f22c6fd2a71aa57ce11b7ac14aac17ae03750cc8a55ecf41f2ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
